server:
  port: 8083

spring:
  application:
    name: order-service
  # datasource:
  #   url: jdbc:h2:mem:orderdb
  #   username: sa
  #   password:
  #   driver-class-name: org.h2.Driver
  # jpa:
  #   hibernate:
  #     ddl-auto: update
  #   show-sql: true
  #   database-platform: org.hibernate.dialect.H2Dialect
  # h2:
  #   console:
  #     enabled: true  # Habilita la consola H2
  #     path: /h2-console  # Ruta para acceder a la consola

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
