server:
  port: 8081

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:h2:mem:productdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    #database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true  # Habilita la consola H2
      path: /h2-console  # Ruta para acceder a la consola

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  gateway:
    enabled: true

# spring:
#   application:
#     name: product-service
#   datasource:
#     url: jdbc:h2:mem:productsdb
#     driver-class-name: org.h2.Driver
#     username: sa
#     password:
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
# server:
#   port: 8081
  
 